### PR TITLE
trie: fix deletion of non leaf nodes

### LINKED ISSUE #152: Errors when withdrawing previously added VRP
While testing the new rpki-validator v3, people at RIPE found a problem with the RTRlib:
> We found one issue testing with RTRLib that we believe is not us: we got errors from RTRLib when we withdraw VRPs - even though the same VRP was just reported as added.

The rpki-rtr server they are using is here (rpm package, use Centos7):
https://github.com/RIPE-NCC/rpki-validator-3/wiki/RIPE-NCC-RPKI-Validator-3-beta-tester-page

Details about feeding test data to that rpki-rtr server, to reproduce the RTRlib error:

> You can change properties for the validator and rtr server in these files (restart required):
/etc/rpki-validator-3/application.properties
/etc/rpki-rtr-server/application.properties
The best way to test the RTR server may be to modify the ‘rpki.validator.validated.roas.uri’ property to point to somewhere other than the actual validator, and put some (small) json file there that follows the same format. I have not tried it, but it may work if you use a ‘file:///' url.

### PR DESCRIPTION
**Pull request by mroethke**
When a non leaf node is deleted one if its childs will takes its place.
The selected child must be the one with the shorter prefix length.
If the one with the longer prefix length is selected the node with the
shorter prefix length will be buried, meaning the search algorithm will
not find it anymore.

Fixes #152

### CODE REVIEW

File: tests/test_pfx.c [hunk 1]
```diff
@@ -330,18 +330,25 @@ static void pfx_table_test(void)
 	printf("pfx_table_test successful\n");
 }
 
+static void create_ip4_pfx_record(struct pfx_record *pfx, uint32_t asn,
+			       const char *ip, uint8_t min_mask_len,
```
Comment (smlng) [inline tests/test_pfx.c]: indention looks off? not aligned with parentheses above?

File: tests/test_pfx.c [hunk 2]
```diff
@@ -363,12 +370,37 @@ static void test_issue99(void)
...
+	create_ip4_pfx_record(&records[5], 6, "213.175.86.0", 24, 24);
+
+	for (size_t i = 0; i < 6; i++) {
+		assert(pfx_table_add(&pfxt, &records[i]) == PFX_SUCCESS);
+	}
+
+	for (size_t i = 0; i < 6; i++) {
+		assert(pfx_table_remove(&pfxt, &records[i]) == PFX_SUCCESS);
+	}
+
```
Comment (smlng) [inline tests/test_pfx.c]: remove empty lines

File: tests/test_pfx.c [hunk 3]
```diff
@@ -363,12 +370,37 @@ static void test_issue99(void)
 	pfx_table_free(&pfxt);
 }
 
+static void test_issue152(void)
+{
+	struct pfx_table pfxt;
+	struct pfx_record *records = calloc(6, sizeof(struct pfx_record));
```
Comment (smlng) [inline tests/test_pfx.c]: unsure myself, but why not use `struct pfx_record records[6];` instead?

File: tests/test_pfx.c (hunk 1 above)
Comment (smlng) [reply tests/test_pfx.c]: but maybe my browser is to blame here ...

Comment (reuteran) [reply tests/test_pfx.c]: indent is off on my screen too

File: tests/test_pfx.c (hunk 2 above)
Comment (reuteran) [reply tests/test_pfx.c]: free() statement missing for 'records'?

File: tests/test_pfx.c (hunk 3 above)
Comment (mroethke) [reply tests/test_pfx.c]: No specific reason, I want initialized memory there and apparently calloc occurred to me before memset did.

**Comment by smlng** [comment]
@reuteran are we good here?
