### PR TITLE
SSH fixes

### LINKED ISSUE #250: Extend SSH transport to allow for password authentication
### Description of current state
In case of SSH transport, only key-based authentication is allowed.

### Improvement
Allow also for password-based authentication.

### Useful links
Can be tested using https://github.com/cloudflare/gortr.

### PR DESCRIPTION
**Pull request by mroethke**
### Contribution description
Several fixes for the ssh transport
- the log prefix did sometimes indicate the wrong function
- add support for password authentication
- properly check malloc return values in ssh init
- fix a deprecation warning from libssh
- fix constant spinning on send
- check return values of libssh functions better and translate them explicitly to our internal ones

### Issues/PRs references
fixes #212 
fixes #250

### CODE REVIEW

**Comment by mroethke** [comment]
ci:rerun

File: tools/rtrclient.c [hunk 1]
```diff
@@ -230,6 +247,45 @@ static bool is_readable_file(const char *str)
...
+		} else if ((str[i] & UTF8_FOUR_BYTE_MASK) == UTF8_FOUR_BYTE_PREFIX && i + 3 < len &&
+			   (str[i + 1] & UTF8_SUBSEQUENT_BYTE_MASK) == UTF8_SUBSEQUENT_BYTE_PREFIX &&
+			   (str[i + 2] & UTF8_SUBSEQUENT_BYTE_MASK) == UTF8_SUBSEQUENT_BYTE_PREFIX &&
+			   (str[i + 3] & UTF8_SUBSEQUENT_BYTE_MASK) == UTF8_SUBSEQUENT_BYTE_PREFIX) {
+			i += 3;
+			continue;
+		}
+
+		// if none of the conditions matched. The string contains at least one character that are not valid utf8
+		return false;
```
[the remark this answers is not in the document]
Comment (smlng) [reply tools/rtrclient.c:283]:
```
int i = 0;
bool is_utf8 = true;
while (i < len && is_utf8) {
    if (//1 byte) {
        i += 1;
    }
    else if (//2 bytes) {
        i += 2;
    }
    ...
    else {
        is_utf8 = false;
    }
}
return is_utf8;
```

[the remark this answers is not in the document]
Comment (smlng) [reply tools/rtrclient.c:283]: however, just a suggestion not a blocker

File: tools/rtrclient.c [hunk 2]
```diff
@@ -230,6 +247,45 @@ static bool is_readable_file(const char *str)
...
+static bool is_utf8(const char *str)
+{
+	size_t len = strlen(str);
+
+	for (size_t i = 0; i <= len; ++i) {
+		// check if current byte is a single utf char
+		if ((str[i] & UTF8_ONE_BYTE_MASK) == UTF8_ONE_BYTE_PREFIX) {
+			continue;
+
+			// check if current byte is the start of a two byte utf8 char and validate subsequent bytes
```
Comment (smlng) [inline tools/rtrclient.c:260]: minor: indention of comment not aligned like comment above? Same for next 2 `else if`.

File: rtrlib/transport/ssh/ssh_transport.c [hunk 3]
```diff
@@ -250,41 +250,86 @@ RTRLIB_EXPORT int tr_ssh_init(const struct tr_ssh_config *config, struct tr_sock
...
+	if (!ssh_socket->config.username)
+		goto error;
 
 	if ((config->password && config->client_privkey_path) || (!config->password && !config->client_privkey_path))
 		return TR_ERROR;
 
-	if (config->bindaddr)
+	if (config->bindaddr) {
 		ssh_socket->config.bindaddr = lrtr_strdup(config->bindaddr);
-	else
```
[the remark this answers is not in the document]
Comment (mroethke) [reply rtrlib/transport/ssh/ssh_transport.c]: bindaddr is optional. We must first check if it is set and than if the strdup was successful.

File: tools/rtrclient.c [hunk 4]
```diff
@@ -230,6 +247,45 @@ static bool is_readable_file(const char *str)
...
+			// check if current byte is the start of a four byte utf8 char and validate subsequent bytes
+		} else if ((str[i] & UTF8_FOUR_BYTE_MASK) == UTF8_FOUR_BYTE_PREFIX && i + 3 < len &&
+			   (str[i + 1] & UTF8_SUBSEQUENT_BYTE_MASK) == UTF8_SUBSEQUENT_BYTE_PREFIX &&
+			   (str[i + 2] & UTF8_SUBSEQUENT_BYTE_MASK) == UTF8_SUBSEQUENT_BYTE_PREFIX &&
+			   (str[i + 3] & UTF8_SUBSEQUENT_BYTE_MASK) == UTF8_SUBSEQUENT_BYTE_PREFIX) {
+			i += 3;
+			continue;
+		}
+
+		// if none of the conditions matched. The string contains at least one character that are not valid utf8
```
[the remark this answers is not in the document]
Comment (mroethke) [reply tools/rtrclient.c]: fixed

File: tools/rtrclient.c [hunk 5]
```diff
@@ -230,6 +247,45 @@ static bool is_readable_file(const char *str)
 	return is_file(str);
 }
 
+#ifdef RTRLIB_HAVE_LIBSSH
+static bool is_utf8(const char *str)
+{
+	size_t len = strlen(str);
+
+	for (size_t i = 0; i <= len; ++i) {
+		// check if current byte is a single utf char
```
[the remark this answers is not in the document]
Comment (mroethke) [reply tools/rtrclient.c]: fixed

File: tools/rtrclient.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (mroethke) [reply tools/rtrclient.c:283]: I would argue that the current form is more readable, because the continue makes it clear that there is nothing relevant after the if.

File: tools/rtrclient.c (hunk 2 above)
Comment (mroethke) [reply tools/rtrclient.c]: fixed

File: tools/rtrclient.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (smlng) [reply tools/rtrclient.c:283]: I still disagree, all `continues` are only required bc `return false` is not in an `else` branch. A curious developer will tend to look what is skipped over by `continue` anyway - and will discover its only the `return false`. I'm not against using `continue` in general, but here it seems unnecessary to me.

Further, I think it is suboptimal that `i` is manipulated twice, i.e., in the loop statement (`++i`) and by all `else if` cases. Also it is counter intuitive that `i` is increase by `byte-size - 1` - I admit that the for-loop avoids accidentally creating an invite loop, hence I still find something like

```
int i = 0;
while (i < len) {
    if (// 1 byte utf8) {
        //do stuff
        i += 1;
    }
    else if (//2 byte utf8) {
        // do stuff
        i += 2;
    }
    ...
    else {
        return false;
    }
}
return true;
```

easier to understand and less error prone.

File: tools/rtrclient.c [hunk 6]
```diff
@@ -230,6 +247,45 @@ static bool is_readable_file(const char *str)
 	return is_file(str);
 }
 
+#ifdef RTRLIB_HAVE_LIBSSH
+static bool is_utf8(const char *str)
+{
+	size_t len = strlen(str);
+
+	for (size_t i = 0; i <= len; ++i) {
```
Comment (smlng) [inline tools/rtrclient.c:255]: shouldn't this be `i < len` instead of `i <= len`?

Comment (Arvedui) [reply tools/rtrclient.c]: Yes. Though in practice i does not matter because the last byte is always the terminating null byte.
I fixed it anyway of course.

File: tools/rtrclient.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (Arvedui) [reply tools/rtrclient.c]: I'm starting to think that you are right. Change it accordingly.

[the remark this answers is not in the document]
Comment (mroethke) [reply tools/rtrclient.c]: I'm starting to think that you are right, changed it accordingly.

File: tools/rtrclient.c (hunk 6 above)
Comment (mroethke) [reply tools/rtrclient.c]: Yes. fixed.

**Comment by mroethke** [comment]
I also noticed two additional problems myself.
1. I forgot to amend the help string and the man page
2. The option `-s` to force the rtrclient to interpret the string as a path to a private key collided with another global option. I switched it to use `-r`.

**Comment by mroethke** [comment]
ping @pguibert6WIND

File: rtrlib/transport/ssh/ssh_transport.c [hunk 7]
```diff
@@ -137,14 +137,29 @@ int tr_ssh_open(void *socket)
 		goto error;
 	}
 
+	if (config->client_privkey_path) {
+		SSH_DBG("%s: Trying publickey authentication", ssh_socket, __func__);
+		ssh_options_set(ssh_socket->session, SSH_OPTIONS_IDENTITY, config->client_privkey_path);
+
+		int rtval;
+
```
Comment (pguibert6WIND) [inline rtrlib/transport/ssh/ssh_transport.c:149]: is it possible to swap the order:
'int rtval'
before ssh_options_set, 

like most of C programs ?

File: rtrlib/transport/ssh/ssh_transport.c [hunk 8]
```diff
@@ -304,6 +319,11 @@ RTRLIB_EXPORT int tr_ssh_init(const struct tr_ssh_config *config, struct tr_sock
 	else
 		ssh_socket->config.connect_timeout = config->connect_timeout;
 
+	if (config->password)
+		ssh_socket->config.password = lrtr_strdup(config->password);
+	else
```
Comment (pguibert6WIND) [inline rtrlib/transport/ssh/ssh_transport.c]: how is it freed  ?

File: cmake/modules/FindLibSSH.cmake [hunk 9]
```diff
@@ -73,6 +73,10 @@ else (LIBSSH_LIBRARIES AND LIBSSH_INCLUDE_DIRS)
                 string(REGEX MATCH "[0-9]+" LIBSSH_VERSION_PATCH ${LIBSSH_VERSION_PATCH})
 
                 set(LibSSH_VERSION ${LIBSSH_VERSION_MAJOR}.${LIBSSH_VERSION_MINOR}.${LIBSSH_VERSION_PATCH})
+                set(LibSSH_VERSION_MAJOR ${LIBSSH_VERSION_MAJOR})
+                set(LibSSH_VERSION_MINOR ${LIBSSH_VERSION_MINOR})
+                set(LibSSH_VERSION_PATCH ${LIBSSH_VERSION_PATCH})
+                set(LibSSH_VERSION_COUNT "3")
```
Comment (pguibert6WIND) [inline cmake/modules/FindLibSSH.cmake:80]: why 3?

File: rtrlib/transport/ssh/ssh_transport.c [hunk 10]
```diff
@@ -299,6 +299,9 @@ RTRLIB_EXPORT int tr_ssh_init(const struct tr_ssh_config *config, struct tr_sock
 	ssh_socket->config.port = config->port;
 	ssh_socket->config.username = lrtr_strdup(config->username);
 
+	if ((config->password && config->client_privkey_path) || (!config->password && !config->client_privkey_path))
+		return TR_ERROR;
+
```
Comment (pguibert6WIND) [inline rtrlib/transport/ssh/ssh_transport.c:321]: could not we set  a priority ? first privkey, trhen password if privkey fails ?

File: rtrlib/transport/ssh/ssh_transport.c [hunk 11]
```diff
@@ -290,46 +290,91 @@ RTRLIB_EXPORT int tr_ssh_init(const struct tr_ssh_config *config, struct tr_sock
...
 	ssh_socket->channel = NULL;
 	ssh_socket->session = NULL;
 	ssh_socket->config.host = lrtr_strdup(config->host);
+	if (!ssh_socket->config.host)
+		goto error;
 	ssh_socket->config.port = config->port;
+
 	ssh_socket->config.username = lrtr_strdup(config->username);
+	if (!ssh_socket->config.username)
+		goto error;
```
Comment (pguibert6WIND) [inline rtrlib/transport/ssh/ssh_transport.c:318]: move it at same level as config.host. it avoids strdupping (config->username) for notthing.

File: rtrlib/transport/ssh/ssh_transport.c [hunk 12]
```diff
@@ -243,11 +243,10 @@ int tr_ssh_recv_async(const struct tr_ssh_socket *tr_ssh_sock, void *buf, const
 	return rtval;
 }
```
Comment (pguibert6WIND) [inline rtrlib/transport/ssh/ssh_transport.c:245]: is commit log consistent with modified code ? (ssh_send and tr_ssh recv ?)

**Review by pguibert6WIND — CHANGES_REQUESTED** [review]

File: rtrlib/transport/ssh/ssh_transport.c (hunk 7 above)
Comment (mroethke) [reply rtrlib/transport/ssh/ssh_transport.c:149]: I prefer to declare variables were they are first used not at the beginning at the block. The declaration is only "freestanding" because it wanted to avoid duplication the declaration in the following if/else macro.

File: rtrlib/transport/ssh/ssh_transport.c (hunk 8 above)
Comment (mroethke) [reply rtrlib/transport/ssh/ssh_transport.c]: it is freed in `tr_ssh_free`

File: cmake/modules/FindLibSSH.cmake (hunk 9 above)
Comment (mroethke) [reply cmake/modules/FindLibSSH.cmake:80]: Because the version number of libssh has 3 components. It a standard variable that is expected to be exported by cmakd find scripts.

File: rtrlib/transport/ssh/ssh_transport.c (hunk 10 above)
Comment (mroethke) [reply rtrlib/transport/ssh/ssh_transport.c:321]: I don't think that makes sense in non interactive environments.

File: rtrlib/transport/ssh/ssh_transport.c (hunk 11 above)
Comment (mroethke) [reply rtrlib/transport/ssh/ssh_transport.c:318]: You are saying I should check if username is set before strduping it?

File: rtrlib/transport/ssh/ssh_transport.c (hunk 12 above)
Comment (mroethke) [reply rtrlib/transport/ssh/ssh_transport.c:245]: fixed in my local branch

**Comment by mroethke** [comment]
ping @pguibert6WIND

**Comment by waehlisch** [comment]
ci:rerun
