### PR TITLE
Fix rtr_stop blocking behavior of tr_open

### LINKED ISSUE #254: RTRlib/ some delay when stopping a RPKI connection with FRR
### Description
When using with FRR, BGP RPKI sometimes freezes with SSH configuration

### reproduction
I did it with [0]
with a RPKI configuration that we delete, and we recreate a new one. we can observe a 12 second delay between the calls to pthread_cancel() and pthread_join()
I do it with a ssh config, but I dont need any remote ssh server to do  that.

[0] https://github.com/FRRouting/frr/pull/5015

note: the problem happens when using 22 port, but not when using != 22 port.
### Expected results
```
Mar 03 15:24:02 bgpd[31859]: (2020/03/03 15:24:02:819582): RTR Socket: pthread_cancel()
Mar 03 15:24:02  bgpd[31859]: (2020/03/03 15:24:02:819600): RTR Socket: pthread_join()
Mar 03 15:24:02  bgpd[31859]: (2020/03/03 15:25:14:935700): SSH Transport(abcd@1.0.0.1:22): tr_ssh_init: opening SSH connection failed
```

### Actual results
```
Mar 03 15:24:02 bgpd[31859]: (2020/03/03 15:24:02:819582): RTR Socket: pthread_cancel()
Mar 03 15:24:02  bgpd[31859]: (2020/03/03 15:24:02:819600): RTR Socket: pthread_join()
Mar 03 15:25:14  bgpd[31859]: (2020/03/03 15:25:14:935700): SSH Transport(abcd@1.0.0.1:22): tr_ssh_init: opening SSH connection failed
```
### Analysis
it looks like in rtr.c file, we call `pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &oldcancelstate);` in the pthread created. then I guess the following calls will be kind of blocked.
```
rtr.c:          RTR_DBG1("pthread_cancel()");
rtr.c:          pthread_cancel(rtr_socket->thread_id);
rtr.c:          RTR_DBG1("pthread_join()");
rtr.c:          pthread_join(rtr_socket->thread_id, NULL);
```

### PR DESCRIPTION
**Pull request by mroethke**
### Contribution description
Since the move from pthread_kill to pthread_cancel a rtr_socket could
not be stopped immediately if it was in the tr_open call.
cancelability could not be enabled for that function because it holds
local resources.
This enables cancalability locally for the only blocking call in
tr_tcp_open and tr_ssh_open respectively.

### Testing procedure

Call `rtr_mgr_stop` shortly after `rtr_mgr_start` and make sure that the connection attempt does not succeed or fail immediately. For instance by dropping the packets via the firewall.

Without this patch `rtr_mgr_stop` hangs until the connection attempts times out.

### Issues/PRs references
Fixes #254

### CODE REVIEW

File: rtrlib/transport/ssh/ssh_transport.c [hunk 1]
```diff
@@ -86,10 +89,47 @@ int tr_ssh_open(void *socket)
...
+			SSH_DBG1("tr_ssh_init: opening SSH connection failed", ssh_socket);
+			goto error;
+		} else if (ret == SSH_AGAIN) {
+			socket_t fd = ssh_get_fd(ssh_socket->session);
+
+			fd_set rfds;
+
+			FD_ZERO(&rfds);
+			FD_SET(fd, &rfds);
+			struct timeval tv = { 30, 0 };
```
Comment (smlng) [inline rtrlib/transport/ssh/ssh_transport.c:108]: add comment that this is a timeout of 30s for `select` below. Also maybe change variable name to `timeout`?

File: rtrlib/transport/tcp/tcp_transport.c [hunk 2]
```diff
@@ -91,13 +136,65 @@ int tr_tcp_open(void *tr_socket)
...
+		pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, &oldcancelstate);
+		int ret = select(tcp_socket->socket + 1, NULL, &wfds, NULL, NULL);
+
+		pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &oldcancelstate);
+
+		if (ret < 0) {
+			TCP_DBG("Could not select tcp socket, %s", tcp_socket, strerror(errno));
+			goto end;
+
+		} else if (ret == 0) {
```
Comment (smlng) [inline rtrlib/transport/tcp/tcp_transport.c:178]: can this actually happen, as there is no timeout given in `select` above?

**Review by smlng — COMMENTED** [review]
minor stuff

File: rtrlib/transport/tcp/tcp_transport.c (hunk 2 above)
Comment (mroethke) [reply rtrlib/transport/tcp/tcp_transport.c:178]: I'm wondering why I used select without a timeout there. I do not remember a specific reason and it does seem wrong to me right now.
I think I will just add a timeout like I have in the ssh implementation.

File: rtrlib/transport/ssh/ssh_transport.c [hunk 3]
```diff
@@ -86,10 +89,47 @@ int tr_ssh_open(void *socket)
...
+			int oldcancelstate;
+
+			/* Enable cancalability for the select call
+			 * to prevent rtr_stop from blocking for a long time.
```
Comment (pguibert6WIND) [inline rtrlib/transport/ssh/ssh_transport.c:112]: typo: cancellability

File: rtrlib/transport/tcp/tcp_transport.c [hunk 4]
```diff
@@ -91,13 +136,65 @@ int tr_tcp_open(void *tr_socket)
...
+		res = NULL;
+
+		fd_set wfds;
+
+		FD_ZERO(&wfds);
+		FD_SET(tcp_socket->socket, &wfds);
+		int oldcancelstate;
+
+		/* Enable cancalability for the select call
+		 * to prevent rtr_stop from blocking for a long time.
```
Comment (pguibert6WIND) [inline rtrlib/transport/tcp/tcp_transport.c:165]: typo: cancelability

File: rtrlib/transport/ssh/ssh_transport.c (hunk 1 above)
Comment (pguibert6WIND) [reply rtrlib/transport/ssh/ssh_transport.c:108]: > add comment that this is a timeout of 30s for `select` below. Also maybe change variable name to `timeout`?

+1. agreed. by the way, having the timeout value configurable would be a nice to have. ( separate ticket, or separate commit )

**Review by pguibert6WIND — CHANGES_REQUESTED** [review]
actually, select() is used because timeout param can be used.
if you had not the timeout to handle, you could have used read() to simplify the code.

actually, select() is mandatory with timeout.

File: rtrlib/transport/ssh/ssh_transport.c (hunk 1 above)
Comment (mroethke) [reply rtrlib/transport/ssh/ssh_transport.c]: > add comment that this is a timeout of 30s for `select` below. Also maybe change variable name to `timeout`?

done


> > add comment that this is a timeout of 30s for `select` below. Also maybe change variable name to `timeout`?
> 
> +1. agreed. by the way, having the timeout value configurable would be a nice to have. ( separate ticket, or separate commit )

Yea, making this configurable is probably a good idea. Will add this to this PR.

File: rtrlib/transport/ssh/ssh_transport.c (hunk 3 above)
Comment (mroethke) [reply rtrlib/transport/ssh/ssh_transport.c:113]: done

File: rtrlib/transport/ssh/ssh_transport.h [hunk 5]
```diff
@@ -45,6 +45,7 @@
  *	  is made. The returned socket is expected to be ready for use (e.g.
  *	  in state established), and must use a reliably stream-oriented transport.
  *	  When new_socket() is used, host, port, and bindaddr are not used.
+ * @param connect_timeout Time in seconds to wait for a succeccfull connection. Defaults to 30 seconds
  */
```
Comment (pguibert6WIND) [inline rtrlib/transport/ssh/ssh_transport.h:49]: nit: s/succeccfull/successfull

File: rtrlib/transport/tcp/tcp_transport.h [hunk 6]
```diff
@@ -35,13 +35,15 @@
  *	  is made. The returned socket is expected to be ready for use (e.g.
  *	  in state established), and must use a reliably stream-oriented transport.
  *	  When new_socket() is used, host, port, and bindaddr are not used.
+ * @param connect_timeout Time in seconds to wait for a succeccfull connection. Defaults to 30 seconds
  */
```
Comment (pguibert6WIND) [inline rtrlib/transport/tcp/tcp_transport.h:39]: s/succeccfull/successfull

**Review by pguibert6WIND — CHANGES_REQUESTED** [review]
2 typo comments.

I hesitate to ask you to move TIMEOUT define value to transport header.
or to add on doxygen generated documentation a seealso information so that people can easily identify the timeout by default.

as for the latter, I don't know how to do it with doxygen, and the first is self contained, I think it is ok like that.

thanks.

File: rtrlib/transport/ssh/ssh_transport.h (hunk 5 above)
Comment (mroethke) [reply rtrlib/transport/ssh/ssh_transport.h:49]: actually it is [sucessful](https://www.merriam-webster.com/dictionary/successful), but it is wrong either way, so thank for pointing that out.

**Comment by mroethke** [comment]
ci:rerun

**Comment by mroethke** [comment]
ci:rerun

**Comment by mroethke** [comment]
> I hesitate to ask you to move TIMEOUT define value to transport header.
> or to add on doxygen generated documentation a seealso information so that people can easily identify the timeout by default.
> 
> as for the latter, I don't know how to do it with doxygen, and the first is self contained, I think it is ok like that.

I moved the connect timeout to the transport header and referenced the define instead of writing out the timeout. I think that is the best we can do with doxygen.

**Comment by pguibert6WIND** [comment]
Hi Marcel,
I would be ok to approve the pr, but first, could you clarify me why codecov/patch and codecov/project fails ?
if this is unrelated, then I will approve your pr.
thanks,

**Comment by mroethke** [comment]
Frankly codecov is pretty broken, at least for us. Most of the lines that are not covered anymore did not change and changes made should not have an impact. I'm not sure why it is so broken, but it unfortunately is. I think it is still nice as ballpark metric, but should not be used to block pull request except in very extreme cases.

**Review by pguibert6WIND — APPROVED** [review]
